In [32]:
import pandas as pd
import numpy as np
import seaborn as sns
from matplotlib import pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.feature_selection import RFE
from sklearn.preprocessing import PolynomialFeatures, StandardScaler
import statsmodels
from statsmodels.formula.api import ols
from sklearn.model_selection import train_test_split
from sklearn.dummy import DummyRegressor
from statsmodels.tools.eval_measures import rmse
from statsmodels.api import qqplot
from scipy import stats
from sklearn.preprocessing import OneHotEncoder
from folium.plugins import FastMarkerCluster
from sklearn.metrics import r2_score
import matplotlib.ticker as ticker
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
from sklearn.metrics import plot_confusion_matrix
from sklearn.metrics import roc_auc_score, plot_roc_curve

In [56]:
vaccinetrainingdf = pd.read_csv("data/training_set_features.csv")
vaccinetestdf = pd.read_csv("data/test_set_features.csv")
vaccinelabelsdf = pd.read_csv("data/training_set_labels.csv")

In [34]:
vaccinetrainingdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 36 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   respondent_id                26707 non-null  int64  
 1   h1n1_concern                 26615 non-null  float64
 2   h1n1_knowledge               26591 non-null  float64
 3   behavioral_antiviral_meds    26636 non-null  float64
 4   behavioral_avoidance         26499 non-null  float64
 5   behavioral_face_mask         26688 non-null  float64
 6   behavioral_wash_hands        26665 non-null  float64
 7   behavioral_large_gatherings  26620 non-null  float64
 8   behavioral_outside_home      26625 non-null  float64
 9   behavioral_touch_face        26579 non-null  float64
 10  doctor_recc_h1n1             24547 non-null  float64
 11  doctor_recc_seasonal         24547 non-null  float64
 12  chronic_med_condition        25736 non-null  float64
 13  child_under_6_mo

In [35]:
vaccinetrainingdf.head()

respondent_id  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0              0           1.0             0.0                        0.0   
1              1           3.0             2.0                        0.0   
2              2           1.0             1.0                        0.0   
3              3           1.0             1.0                        0.0   
4              4           2.0             1.0                        0.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   0.0                   0.0                    0.0   
1                   1.0                   0.0                    1.0   
2                   1.0                   0.0                    0.0   
3                   1.0                   0.0                    1.0   
4                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          0.0                      1.0   
1                          0.0                      1.0   
2                          0.0                      0.0   
3                          1.0                      0.0   
4                          1.0                      0.0   

   behavioral_touch_face  doctor_recc_h1n1  doctor_recc_seasonal  \
0                    1.0               0.0                   0.0   
1                    1.0               0.0                   0.0   
2                    0.0               NaN                   NaN   
3                    0.0               0.0                   1.0   
4                    1.0               0.0                   0.0   

   chronic_med_condition  child_under_6_months  health_worker  \
0                    0.0                   0.0            0.0   
1                    0.0                   0.0            0.0   
2                    1.0                   0.0            0.0   
3                    1.0                   0.0            0.0   
4                    0.0                   0.0            0.0   

   health_insurance  opinion_h1n1_vacc_effective  opinion_h1n1_risk  \
0               1.0                          3.0                1.0   
1               1.0                          5.0                4.0   
2               NaN                          3.0                1.0   
3               NaN                          3.0                3.0   
4               NaN                          3.0                3.0   

   opinion_h1n1_sick_from_vacc  opinion_seas_vacc_effective  \
0                          2.0                          2.0   
1                          4.0                          4.0   
2                          1.0                          4.0   
3                          5.0                          5.0   
4                          2.0                          3.0   

   opinion_seas_risk  opinion_seas_sick_from_vacc      age_group  \
0                1.0                          2.0  55 - 64 Years   
1                2.0                          4.0  35 - 44 Years   
2                1.0                          2.0  18 - 34 Years   
3                4.0                          1.0      65+ Years   
4                1.0                          4.0  45 - 54 Years   

          education   race     sex             income_poverty marital_status  \
0        < 12 Years  White  Female              Below Poverty    Not Married   
1          12 Years  White    Male              Below Poverty    Not Married   
2  College Graduate  White    Male  <= $75,000, Above Poverty    Not Married   
3          12 Years  White  Female              Below Poverty    Not Married   
4      Some College  White  Female  <= $75,000, Above Poverty        Married   

  rent_or_own   employment_status hhs_geo_region                census_msa  \
0         Own  Not in Labor Force       oxchjgsf                   Non-MSA   
1        Rent            Employed       bhuqouqj  MSA, Not Principle  City   
2         Own         

In [36]:
vaccinetestdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26708 entries, 0 to 26707
Data columns (total 36 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   respondent_id                26708 non-null  int64  
 1   h1n1_concern                 26623 non-null  float64
 2   h1n1_knowledge               26586 non-null  float64
 3   behavioral_antiviral_meds    26629 non-null  float64
 4   behavioral_avoidance         26495 non-null  float64
 5   behavioral_face_mask         26689 non-null  float64
 6   behavioral_wash_hands        26668 non-null  float64
 7   behavioral_large_gatherings  26636 non-null  float64
 8   behavioral_outside_home      26626 non-null  float64
 9   behavioral_touch_face        26580 non-null  float64
 10  doctor_recc_h1n1             24548 non-null  float64
 11  doctor_recc_seasonal         24548 non-null  float64
 12  chronic_med_condition        25776 non-null  float64
 13  child_under_6_mo

In [37]:
pd.set_option('max_columns', None)
vaccinetestdf.head()

respondent_id  h1n1_concern  h1n1_knowledge  behavioral_antiviral_meds  \
0          26707           2.0             2.0                        0.0   
1          26708           1.0             1.0                        0.0   
2          26709           2.0             2.0                        0.0   
3          26710           1.0             1.0                        0.0   
4          26711           3.0             1.0                        1.0   

   behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                   1.0                   0.0                    1.0   
1                   0.0                   0.0                    0.0   
2                   0.0                   1.0                    1.0   
3                   0.0                   0.0                    0.0   
4                   1.0                   0.0                    1.0   

   behavioral_large_gatherings  behavioral_outside_home  \
0                          1.0                      0.0   
1                          0.0                      0.0   
2                          1.0                      1.0   
3                          0.0                      0.0   
4                          1.0                      1.0   

   behavioral_touch_face  doctor_recc_h1n1  doctor_recc_seasonal  \
0                    1.0               0.0                   0.0   
1                    0.0               0.0                   0.0   
2                    1.0               0.0                   0.0   
3                    0.0               1.0                   1.0   
4                    1.0               0.0                   0.0   

   chronic_med_condition  child_under_6_months  health_worker  \
0                    0.0                   0.0            0.0   
1                    0.0                   0.0            0.0   
2                    0.0                   0.0            0.0   
3                    1.0                   0.0            0.0   
4                    0.0                   0.0            1.0   

   health_insurance  opinion_h1n1_vacc_effective  opinion_h1n1_risk  \
0               1.0                          5.0                1.0   
1               0.0                          4.0                1.0   
2               NaN                          5.0                4.0   
3               1.0                          4.0                2.0   
4               1.0                          5.0                2.0   

   opinion_h1n1_sick_from_vacc  opinion_seas_vacc_effective  \
0                          1.0                          5.0   
1                          1.0                          4.0   
2                          2.0                          5.0   
3                          2.0                          4.0   
4                          4.0                          4.0   

   opinion_seas_risk  opinion_seas_sick_from_vacc      age_group  \
0                1.0                          1.0  35 - 44 Years   
1                1.0                          1.0  18 - 34 Years   
2                4.0                          4.0  55 - 64 Years   
3                4.0                          2.0      65+ Years   
4                4.0                          2.0  35 - 44 Years   

          education      race     sex             income_poverty  \
0  College Graduate  Hispanic  Female                  > $75,000   
1          12 Years     White    Male              Below Poverty   
2  College Graduate     White    Male                  > $75,000   
3          12 Years     White  Female  <= $75,000, Above Poverty   
4          12 Years     Black  Female  <= $75,000, Above Poverty   

  marital_status rent_or_own   employment_status hhs_geo_region  \
0    Not Married        Rent            Employed       mlyzmhmf   
1    Not Married        Rent            Employed       bhuqouqj   
2        Married         Own            Employed       lrircsnp   
3        Married         Own  Not in Labor Force       lrirc

In [38]:
vaccinelabelsdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 3 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   respondent_id     26707 non-null  int64
 1   h1n1_vaccine      26707 non-null  int64
 2   seasonal_vaccine  26707 non-null  int64
dtypes: int64(3)
memory usage: 626.1 KB


In [39]:
vaccinelabelsdf['h1n1_vaccine'].value_counts()

0    21033
1     5674
Name: h1n1_vaccine, dtype: int64

In [40]:
X_train = vaccinetrainingdf.copy().drop(['h1n1_knowledge', 'employment_occupation', 'employment_industry', 
                                         'household_children', 'household_adults', 'census_msa', 'hhs_geo_region',
                                        'employment_status', 'rent_or_own', 'marital_status', 'opinion_seas_sick_from_vacc',
                                        'opinion_seas_risk', 'health_insurance', 'child_under_6_months','health_worker',
                                        ], axis = 1)
X_test = vaccinetestdf.copy().drop(['h1n1_knowledge'], axis = 1)
y_train = vaccinetrainingdf['h1n1_knowledge']
y_test = vaccinetestdf['h1n1_knowledge']

In [41]:
X_train_nona = X_train.dropna()

In [42]:
X_train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   respondent_id                26707 non-null  int64  
 1   h1n1_concern                 26615 non-null  float64
 2   behavioral_antiviral_meds    26636 non-null  float64
 3   behavioral_avoidance         26499 non-null  float64
 4   behavioral_face_mask         26688 non-null  float64
 5   behavioral_wash_hands        26665 non-null  float64
 6   behavioral_large_gatherings  26620 non-null  float64
 7   behavioral_outside_home      26625 non-null  float64
 8   behavioral_touch_face        26579 non-null  float64
 9   doctor_recc_h1n1             24547 non-null  float64
 10  doctor_recc_seasonal         24547 non-null  float64
 11  chronic_med_condition        25736 non-null  float64
 12  opinion_h1n1_vacc_effective  26316 non-null  float64
 13  opinion_h1n1_ris

In [43]:
X_train_nona.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 19968 entries, 0 to 26706
Data columns (total 21 columns):
 #   Column                       Non-Null Count  Dtype  
---  ------                       --------------  -----  
 0   respondent_id                19968 non-null  int64  
 1   h1n1_concern                 19968 non-null  float64
 2   behavioral_antiviral_meds    19968 non-null  float64
 3   behavioral_avoidance         19968 non-null  float64
 4   behavioral_face_mask         19968 non-null  float64
 5   behavioral_wash_hands        19968 non-null  float64
 6   behavioral_large_gatherings  19968 non-null  float64
 7   behavioral_outside_home      19968 non-null  float64
 8   behavioral_touch_face        19968 non-null  float64
 9   doctor_recc_h1n1             19968 non-null  float64
 10  doctor_recc_seasonal         19968 non-null  float64
 11  chronic_med_condition        19968 non-null  float64
 12  opinion_h1n1_vacc_effective  19968 non-null  float64
 13  opinion_h1n1_ris

In [44]:
X_train

respondent_id  h1n1_concern  behavioral_antiviral_meds  \
0                  0           1.0                        0.0   
1                  1           3.0                        0.0   
2                  2           1.0                        0.0   
3                  3           1.0                        0.0   
4                  4           2.0                        0.0   
...              ...           ...                        ...   
26702          26702           2.0                        0.0   
26703          26703           1.0                        0.0   
26704          26704           2.0                        0.0   
26705          26705           1.0                        0.0   
26706          26706           0.0                        0.0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       0.0                   0.0                    0.0   
1                       1.0                   0.0                    1.0   
2                       1.0                   0.0                    0.0   
3                       1.0                   0.0                    1.0   
4                       1.0                   0.0                    1.0   
...                     ...                   ...                    ...   
26702                   1.0                   0.0                    0.0   
26703                   1.0                   0.0                    1.0   
26704                   1.0                   1.0                    1.0   
26705                   0.0                   0.0                    0.0   
26706                   1.0                   0.0                    0.0   

       behavioral_large_gatherings  behavioral_outside_home  \
0                              0.0                      1.0   
1                              0.0                      1.0   
2                              0.0                      0.0   
3                              1.0                      0.0   
4                              1.0                      0.0   
...                            ...                      ...   
26702                          0.0                      1.0   
26703                          0.0                      0.0   
26704                          1.0                      0.0   
26705                          0.0                      0.0   
26706                          0.0                      0.0   

       behavioral_touch_face  doctor_recc_h1n1  doctor_recc_seasonal  \
0                        1.0               0.0                   0.0   
1                        1.0               0.0                   0.0   
2                        0.0               NaN                   NaN   
3                        0.0               0.0                   1.0   
4                        1.0               0.0                   0.0   
...                      ...               ...                   ...   
26702                    0.0               0.0                   0.0   
26703                    0.0               1.0                   1.0   
26704                    1.0               0.0                   0.0   
26705                    NaN               0.0                   0.0   
26706                    0.0               0.0                   0.0   

       chronic_med_condition  opinion_h1n1_vacc_effective  opinion_h1n1_risk  \
0                        0.0                          3.0                1.0   
1                        0.0                          5.0                4.0   
2                        1.0                          3.0                1.0   
3                        1.0                          3.0                3.0   
4                        0.0                          3.0                3.0   
...                      ...                          ...                ...   
26702                    0.0                          3.0                1.0   
26703                    0.0                       

In [45]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy = 'most_frequent')
imputed_X_train = imputer.fit_transform(X_train)
imputeddf = pd.DataFrame(imputed_X_train)

In [46]:
imputeddf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26707 entries, 0 to 26706
Data columns (total 21 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   0       26707 non-null  object
 1   1       26707 non-null  object
 2   2       26707 non-null  object
 3   3       26707 non-null  object
 4   4       26707 non-null  object
 5   5       26707 non-null  object
 6   6       26707 non-null  object
 7   7       26707 non-null  object
 8   8       26707 non-null  object
 9   9       26707 non-null  object
 10  10      26707 non-null  object
 11  11      26707 non-null  object
 12  12      26707 non-null  object
 13  13      26707 non-null  object
 14  14      26707 non-null  object
 15  15      26707 non-null  object
 16  16      26707 non-null  object
 17  17      26707 non-null  object
 18  18      26707 non-null  object
 19  19      26707 non-null  object
 20  20      26707 non-null  object
dtypes: object(21)
memory usage: 4.3+ MB


In [47]:
#X_train_column_names = X_train.columns.values.tolist()
#type(X_train_column_names)
#list_of_numbers = list(range(0, 21))
#list_of_numbers

In [48]:
#dictionary_of_names = {key: X_train_column_names[0] for key in list_of_numbers}
#dictionary_of_names

In [49]:
#X_train_column_names

In [50]:
dictionary_of_names = {0: 'respondent_id', 1:'h1n1_concern', 2:'behavioral_antiviral_meds',
                       3:'behavioral_avoidance',4:'behavioral_face_mask',5:'behavioral_wash_hands',
                       6:'behavioral_large_gatherings',7:'behavioral_outside_home',8:'behavioral_touch_face',
                       9:'doctor_recc_h1n1',10:'doctor_recc_seasonal',11:'chronic_med_condition',
                      12:'opinion_h1n1_vacc_effective', 13:'opinion_h1n1_risk', 14:'opinion_h1n1_sick_from_vacc',
                       15:'opinion_seas_vacc_effective', 16:'age_group', 17:'education', 18:'race', 19:'sex', 20:'income_poverty'}
imputeddf_plus_column_names = imputeddf.rename(dictionary_of_names, axis = 1)

In [51]:
imputeddf_array = imputeddf_plus_column_names.to_numpy()
type(imputeddf_array)

numpy.ndarray

In [52]:
X_train

respondent_id  h1n1_concern  behavioral_antiviral_meds  \
0                  0           1.0                        0.0   
1                  1           3.0                        0.0   
2                  2           1.0                        0.0   
3                  3           1.0                        0.0   
4                  4           2.0                        0.0   
...              ...           ...                        ...   
26702          26702           2.0                        0.0   
26703          26703           1.0                        0.0   
26704          26704           2.0                        0.0   
26705          26705           1.0                        0.0   
26706          26706           0.0                        0.0   

       behavioral_avoidance  behavioral_face_mask  behavioral_wash_hands  \
0                       0.0                   0.0                    0.0   
1                       1.0                   0.0                    1.0   
2                       1.0                   0.0                    0.0   
3                       1.0                   0.0                    1.0   
4                       1.0                   0.0                    1.0   
...                     ...                   ...                    ...   
26702                   1.0                   0.0                    0.0   
26703                   1.0                   0.0                    1.0   
26704                   1.0                   1.0                    1.0   
26705                   0.0                   0.0                    0.0   
26706                   1.0                   0.0                    0.0   

       behavioral_large_gatherings  behavioral_outside_home  \
0                              0.0                      1.0   
1                              0.0                      1.0   
2                              0.0                      0.0   
3                              1.0                      0.0   
4                              1.0                      0.0   
...                            ...                      ...   
26702                          0.0                      1.0   
26703                          0.0                      0.0   
26704                          1.0                      0.0   
26705                          0.0                      0.0   
26706                          0.0                      0.0   

       behavioral_touch_face  doctor_recc_h1n1  doctor_recc_seasonal  \
0                        1.0               0.0                   0.0   
1                        1.0               0.0                   0.0   
2                        0.0               NaN                   NaN   
3                        0.0               0.0                   1.0   
4                        1.0               0.0                   0.0   
...                      ...               ...                   ...   
26702                    0.0               0.0                   0.0   
26703                    0.0               1.0                   1.0   
26704                    1.0               0.0                   0.0   
26705                    NaN               0.0                   0.0   
26706                    0.0               0.0                   0.0   

       chronic_med_condition  opinion_h1n1_vacc_effective  opinion_h1n1_risk  \
0                        0.0                          3.0                1.0   
1                        0.0                          5.0                4.0   
2                        1.0                          3.0                1.0   
3                        1.0                          3.0                3.0   
4                        0.0                          3.0                3.0   
...                      ...                          ...                ...   
26702                    0.0                          3.0                1.0   
26703                    0.0                       

In [53]:
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder(drop='first', sparse = False)
ohe = encoder.fit_transform(imputeddf_array)

X_train = imputeddf_array
dummy.score(X, y_pred)

In [54]:
encoder.categories_

[array([0, 1, 2, ..., 26704, 26705, 26706], dtype=object),
 array([0.0, 1.0, 2.0, 3.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([0.0, 1.0], dtype=object),
 array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=object),
 array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=object),
 array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=object),
 array([1.0, 2.0, 3.0, 4.0, 5.0], dtype=object),
 array(['18 - 34 Years', '35 - 44 Years', '45 - 54 Years', '55 - 64 Years',
        '65+ Years'], dtype=object),
 array(['12 Years', '< 12 Years', 'College Graduate', 'Some College'],
       dtype=object),
 array(['Black', 'Hispanic', 'Other or Multiple', 'White'], dtype=object),
 array(['Female', 'Male'], dtype=object),
 array(['<= $75,000, Above Poverty', '

In [59]:
h1n1_bin = vaccinetrainingdf[['h1n1_knowledge']]
bins = [0,1]
h1n1_bin['bins'] = pd.cut(x=h1n1_bin['h1n1_knowledge'], bins=bins)
print(h1n1_bin['bins'])

0               NaN
1               NaN
2        (0.0, 1.0]
3        (0.0, 1.0]
4        (0.0, 1.0]
            ...    
26702           NaN
26703           NaN
26704           NaN
26705    (0.0, 1.0]
26706           NaN
Name: bins, Length: 26707, dtype: category
Categories (1, interval[int64]): [(0, 1]]


<ipython-input-59-fee09f170859>:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  h1n1_bin['bins'] = pd.cut(x=h1n1_bin['h1n1_knowledge'], bins=bins)


In [ ]:
from sklearn.dummy import DummyClassifier
dummy = DummyClassifier()
dummy.fit(imputeddf, y_train)
y_pred = dummy.predict(X_train)
y_pred_df = pd.DataFrame(y_pred)
y_pred_df.value_counts()

In [ ]:
from sklearn.model_selection import train_test_split, cross_val_score

dummy_cross_val = cross_val_score(dummy, imputeddf_plus_column_names, y_pred_df)